// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");

function nn(param) {
  var rand = function (min, max) {
    return Random.$$float(1) * (max - min) + min;
  };
  console.log(rand(2, 3));
  console.log(Random.$$float(1));
  var drawP = function (parent, text) {
    var elem = document.createElement("p");
    elem.innerText = text;
    parent.appendChild(elem);
    
  };
  var root = document.createElement("div");
  root.id = "root";
  drawP(root, "(0,0)");
  document.body.appendChild(root);
  
}

nn(undefined);

exports.nn = nn;
/*  Not a pure module */
