// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var ReasonReact = require("reason-react/src/legacy/ReasonReact.bs.js");
var Component1$ReactTemplate = require("./Component1.bs.js");
var Component2$ReactTemplate = require("./Component2.bs.js");
var NeuralNetwork$ReactTemplate = require("./NeuralNetwork.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component1$ReactTemplate.make("Yello!", [])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component2$ReactTemplate.make("Yello!", [])), "index2");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, NeuralNetwork$ReactTemplate.make("Noob!", [])), "index3");

/*  Not a pure module */
