// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/legacy/ReasonReact.bs.js");

var component = ReasonReact.statelessComponent("NeuralNetwork");

function handleClick(_event, _self) {
  console.log("clicked!");
  
}

function make(message, _children) {
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (self) {
              return React.createElement("div", {
                          onClick: Curry._1(self.handle, handleClick)
                        }, message, React.createElement("svg", {
                              height: "40",
                              width: "40",
                              viewBox: "0 0 20 20",
                              xmlns: "http://www.w3.org/2000/svg"
                            }, React.createElement("circle", {
                                  style: {
                                    fill: "blue"
                                  },
                                  cx: "10",
                                  cy: "10",
                                  r: "10",
                                  xmlns: "http://www.w3.org/2000/svg"
                                }), React.createElement("circle", {
                                  style: {
                                    fill: "white"
                                  },
                                  cx: "10",
                                  cy: "10",
                                  r: "8",
                                  xmlns: "http://www.w3.org/2000/svg"
                                })));
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
/* component Not a pure module */
